### PR TITLE
Change 'gradle' to './gradlew' In CONTRIBUTING.MD

### LINKED ISSUE #12: Build instructions should use ./gradlew instead of gradle
The current version of [`CONTRIBUTING.md`](https://github.com/morganey-lang/morganey-gradle-plugin/blob/992e943cc2968111c12c40eee0bcb0dcc0ba1ff2/CONTRIBUTING.md) recommends to use `gradle` for builds. I don't think that's reliable enough. I recommend to replace `gradle` invocations there with `./gradlew`.

### PR DESCRIPTION
**Pull request by 06needhamt**
Fix #12 
Signed-off-by: Tom Needham 06needhamt@gmail.com

### CODE REVIEW

**Comment by ForNeVeR** [comment]
@06needhamt just a side note, not relevant to the review: it seems to me (and I'm terribly sorry if I'm wrong!) that you're using these `Signed-off-by: Tom Needham <06needhamt@gmail.com>` comments without actual understanding of the commit signing process (**or probably your signature settings're wrong; check them on GitHub**) :)

Please take a look at GitHub documentation: https://help.github.com/articles/signing-commits-using-gpg/

Here's a quick sample of **signed** commit: https://github.com/nodejs/node/commit/0ed8839a279ba2597ae9fc54517030b16116207d (see that **Verify** button? That's it!)

If you really like, you may sign your commits with the git mechanism. Although I personally think that's a bit complex for a newbie like I am, so I don't use it.

And also I think there's no practical purpose in signing the PR message itself :)

_(Probably I'm messing signing the commits with the digital signatures; if that's the case, as I said, I'm sorry.)_

**Review by ForNeVeR — APPROVED** [review]

**Comment by 06needhamt** [comment]
@ForNeVeR I didn't know that i am just used to commiting with `git commit -asm` in the future i will just use `-m` Thanks

**Comment by ForNeVeR** [comment]
I think you need to setup the digital signature if you _really_ want to, but I'm not sure about the intentions. So, well, I'll accept commits with the text signatures, if you wish to sign them. That's okay; thanks.

**Comment by Newlifer** [comment]
I second this!

**Comment by Minoru** [comment]
JFTR: there's [a good short explanation](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for/1962112#1962112) of what "Signed-off-by" really means. It's not directly related to digital signatures, but it makes sense to use one when signing off your commits.

**Pull request merged**
