### PR TITLE
Fix JAR Name In Readme

### PR DESCRIPTION
**Pull request by 06needhamt**
Change `Morganey-Files.jar` to `projectname-version.jar`

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Thank you!

**Comment by ForNeVeR** [comment]
@06needhamt it seems that your local branch has been diverged from master. Could you please create a new branch from the current `master` for your pull request?

**Comment by 06needhamt** [comment]
@ForNeVeR I did, what do you mean it has diverged from master

**Comment by ForNeVeR** [comment]
Take a look at the screenshot:
commit
(I'm sorry for the quality, but I'm not smart enough to preserve screenshot resolution after postprocessing in Inkscape)

**Comment by 06needhamt** [comment]
@ForNeVeR @rexim I'm not entirely sure how to fix this issue

**Comment by ForNeVeR** [comment]
@06needhamt I think you need to `git checkout master && git pull`. And you need to do that every time before creating a new branch from `master`.

Also, I encourage you to learn more about git concepts. It will really make your life easier :)

**Comment by rexim** [comment]
> Also, I encourage you to learn git concepts. It will really make your life easier :)

I also recommend reading first three chapters of https://git-scm.com/book/en/v2

**Pull request merged**
