### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by 06needhamt**
I Added the .travis.yml file but i can't enable it on the Travis website because it says i don't have admin rights

Signed-off-by: Tom Needham 06needhamt@gmail.com

untitled

### CODE REVIEW

**Comment by rexim** [comment]
Let me enable the repo...

**Comment by rexim** [comment]
@06needhamt could you please push some useless change to trigger the travis build?

**Review by rexim — APPROVED** [review]
Great! Once the build is done I'm gonna merge it.

**Comment by rexim** [comment]
@ForNeVeR sorry not waiting for you. :( Travis build is one of the things that should merged ASAP. Please feel free to leave your remarks afterwards.

@06needhamt thanks for setting this up!

**Comment by ForNeVeR** [comment]
I have no remarks except that @06needhamt is doing a good job :+1:

**Pull request merged**
